### ISSUE TITLE
Unavailability of data files

### ISSUE THREAD

**Issue by TapanHP1995** [mansi-k/Stutter-Therapy#1]
I have gone thru the whole paper and I have seen that you have worked a lot on modifying the samples. These scripts would be more useful if you can also share that processed data along with it. I want to test this model and It would be really great if you can provide me the files which you have modified from the original UCLASS dataset.

**Comment by TapanHP1995** [comment]
Also If it is possible can you please share the model code as well? While I can use the files to predict the results it would be really beneficial to re-train the model and do experiements on my own.

**Comment by mansi-k** [comment]
Hi, I added the data pre-processing and model training script files. 
The dataset is available here : https://drive.google.com/drive/folders/16iYlxl8ap-1dNyIxnEdLCaUav21ctCrf?usp=sharing

**Comment by TapanHP1995** [comment]
Thanks a lot for this. It will help me a lot!
